### ISSUE TITLE
Multipanel Atari graphs

### ISSUE THREAD

**Issue by pde** [AI-metrics/master_text#10]
There are a lot of Atari games, and their graphs are currently limited in the number of data points they contain, so it would be great to have them displayed in a slightly less voluminous way, perhaps in two columns at 50% of their current size.

[This page](https://matplotlib.org/examples/pylab_examples/subplots_demo.html) gives some examples of how to do this kind of thing.

Yomna, if you can make a `graph_atari_games` function that renders them all in a nice way, I'll figure out how to get rid of the current Atari graphs at the bottom of the Notebook.

**Comment by void-elf** [comment]
So, you want me to try and combine the axes to save space?

**Comment by void-elf** [comment]
So, I've started working on this and have a very rough-looking preview available:

![selection_014](https://user-images.githubusercontent.com/4513790/26952567-e3f0cbf2-4c5a-11e7-9943-9d1c3384181b.png)

Personally, I think it's a bit hard to read the x-axis, but maybe that doesn't matter if all people care about is the shape of the graph. What do you think @pde?

Also, I only combined the y-axis, because combining the x-axis didn't save us anymore space and was displeasing to look at.

**Comment by pde** [comment]
It wasn't so much combining the axes that seemed important, but having the graphs smaller and in  a 2-column format.  However if the axes can be combined as well that's nice (and that was the first documentation I found that showed how to do 2 column layouts).

In terms of readability for the X axis, I wonder if there's a way to do major / minor axis labels so that you don't need to have all of the characters of the year on every tick.

2016 mar jun sep 2017 mar jun sep, or something along those lines?

**Comment by void-elf** [comment]
I've integrated some of the styling the original graphs had, and here's what they like right now: 
![selection_025](https://user-images.githubusercontent.com/4513790/27320978-56309238-554d-11e7-99f8-6322edec1541.png)

I think the original graphs were much nicer to look at (and easier to read), even though they took up lots of space. Ordering these by (max) target might make them easier to look at, as right now comparing a graph to the one next to it is kind of meaningless because they're in alphabetical order and are sharing a Y-axis.

Here's the needs-refactoring code that I slapped together to produce this: https://gist.github.com/ynasser/25b23942615b8e8d45dfc426ac199cb3 ... in case you want to include it.

**Comment by pde** [comment]
Do you dislike them because of the shared axes, or because you also think they're too small? In the former case maybe we should figure out how to do this without sharing the axes. If they're actually too small, then let's close the ticket (there will be more data in theses graphs soon too I hope, so they'll be doing more visual informing)

**Comment by void-elf** [comment]
I think they're too small. If we're going to be adding more data, then keeping them at their original size is better.

I'm going to close the ticket for now, but we should eventually investigate ways to save space that don't detract from the quality of the figures.
