### ISSUE TITLE
Provide an easy web flow for people adding and editing data

### ISSUE THREAD

**Issue by void-elf** [AI-metrics/master_text#37]
Like this one: https://rodrigob.github.io/are_we_there_yet/build/new_result_form.html

People keep submitting paper requests via issues, but what we want is pull requests. However, we acknowledge that setting up this project locally can be a bit tricky for new developers, so we want to automate PRs via web form submissions.

Whoever does this: when the form has a URL, edit the docs + github issue template to include a link to it.

**Comment by pde** [comment]
Another option would be to allow syncing of measurements for a given metric from a specified Google Sheet, which we could allow anyone to suggest changes to.

**Comment by pde** [comment]
(That would be easy to do on a pure-input basis, somewhat trickier to do bidirectionally but it might be possible)

**Comment by pde** [comment]
Conclusion from meeting:

1. We move the raw data into separate files (probably .py files) rather than having it in the Notebook
2. The Notebook gets to include a pretty table version of the data (#44)
3. There's a link saying [edit this data on Github](https://github.com/AI-metrics/AI-metrics/edit/editable-data/data/reading_comprehension.py) which points to the github web editor for the data file.

**Comment by pde** [comment]
For the record, when we evaluated Google Sheets as the data entry platform, we concluded they weren't a good solution because they don't support anything like a "suggest changes" mode: users can be allowed to edit cells, or allowed to comment, but there isn't a reasonable way for users to edit and admins to review the edits.

If we made the sheet world-editable, we fear that anyone defacing things or entering bad data would create a huge amount of work to disentangle good changes from bad ones, and the tooling in Sheets isn't up to that task.

**Comment by pde** [comment]
What we didn't look at, and perhaps should have, is other cloud spreadsheet options.

**Comment by jekbradbury** [comment]
If you are interested in looking at another cloud option, I'm pretty impressed by http://airtable.com
